wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1634575636
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 13
      - 16
      4: 3.7.11
      5: 0.12.4
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.0001
